<?php

namespace Database\Seeders;

use App\Models\Rate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rates = [
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
            [
                'user_id' => rand(1,10),
                'package_id' => rand(1,3),
                'pt_id' => rand(1,6),
                'star_package' => rand(3,5),
                'star_pt' => rand(3,5),
                'note_package' => "Gói tập tuyệt vời quá",
                'note_pt' => "Huấn luyện viên nhiệt tình",
            ],
        ];
    
        foreach($rates as $item){
            Rate::create($item);
        }
    }
}
